from __future__ import annotations

from typing import Optional

from openai import OpenAI
from app.core.config import settings


_client: Optional[OpenAI] = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        if not settings.OPENAI_API_KEY:
            raise RuntimeError("OPENAI_API_KEY is missing")
        _client = OpenAI(api_key=settings.OPENAI_API_KEY)
    return _client


def llm_generate_markdown(system_prompt: str, user_prompt: str) -> str:
    """
    Returns markdown text generated by the configured OpenAI model.
    Server-side only.
    """
    client = _get_client()

    resp = client.chat.completions.create(
        model=settings.OPENAI_MODEL,
        timeout=settings.OPENAI_TIMEOUT_SECONDS,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.4,
    )

    content = resp.choices[0].message.content or ""
    return content.strip()