"""add pipelines (templates runs steps)

Revision ID: ffe4784a0fac
Revises: 3b0c91a6fb4a
Create Date: 2026-02-24 13:12:50.893539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffe4784a0fac'
down_revision: Union[str, None] = '3b0c91a6fb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_templates_workspace_id'), 'pipeline_templates', ['workspace_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['pipeline_templates.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_created_by_user_id'), 'pipeline_runs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_template_id'), 'pipeline_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_workspace_id'), 'pipeline_runs', ['workspace_id'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_steps_pipeline_run_id'), 'pipeline_steps', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_run_id'), 'pipeline_steps', ['run_id'], unique=False)
    op.drop_index('ix_chunks_tsv_tsvector', table_name='chunks', postgresql_using='gin')
    op.drop_column('chunks', 'tsv_tsvector')
    op.drop_index('ix_embeddings_embedding_vec', table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_embeddings_model', table_name='embeddings')
    op.drop_column('embeddings', 'embedding_vec')
    op.drop_index('ix_sources_type', table_name='sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sources_type', 'sources', ['type'], unique=False)
    op.add_column('embeddings', sa.Column('embedding_vec', sa.NullType(), autoincrement=False, nullable=True))
    op.create_index('ix_embeddings_model', 'embeddings', ['model'], unique=False)
    op.create_index('ix_embeddings_embedding_vec', 'embeddings', ['embedding_vec'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('chunks', sa.Column('tsv_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, COALESCE(text, ''::text))", persisted=True), autoincrement=False, nullable=True))
    op.create_index('ix_chunks_tsv_tsvector', 'chunks', ['tsv_tsvector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_pipeline_steps_run_id'), table_name='pipeline_steps')
    op.drop_index(op.f('ix_pipeline_steps_pipeline_run_id'), table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_pipeline_runs_workspace_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_template_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_by_user_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_templates_workspace_id'), table_name='pipeline_templates')
    op.drop_table('pipeline_templates')
    # ### end Alembic commands ###
